FROM python:3.12-slim
WORKDIR /app

COPY shared ./shared

ARG WORKER
COPY workers/${WORKER}/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY workers/${WORKER}/ .

CMD ["python", "worker.py"]
